version: "3.0"
services:
  tamp_rai:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/home/user/coop_tamp
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/gdm/Xauthority:/home/user/.Xauthority
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ~/.gitconfig:/home/user/.gitconfig:ro
    command: /bin/sh -c "while sleep 1000; do :; done"